{"event": "runner_on_failed", "uuid": "c735e134-3362-473e-aa89-f1bc257a8943", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": true, \"cmd\": [\"virsh\", \"attach-interface\", \"\u2013domain\", \"routers.sourceRouter\", \"\u2013type\", \"network\", \"\u2013source\", \"routers.networkName\", \"\u2013model\", \"virtio\", \"\u2013mac\", \"{stderr_lines:\", \"[],\", \"stdout:\", \"uc5:2a:18:2d:27:41\\\\n,\", \"changed:\", \"True,\", \"failed:\", \"False,\", \"stderr:\", \"u,\", \"rc:\", \"0,\", \"stdout_lines:\", \"[uc5:2a:18:2d:27:41]}\", \"\u2013config\", \"\u2013live\"], \"delta\": \"0:00:00.033103\", \"end\": \"2019-11-10 22:10:18.490999\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2019-11-10 22:10:18.457896\", \"stderr\": \"error: unexpected data '{stderr_lines:'\", \"stderr_lines\": [\"error: unexpected data '{stderr_lines:'\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "counter": 27, "pid": 19961, "created": "2019-11-10T22:10:18.541077", "end_line": 39, "runner_ident": "532f180b-e70b-4e65-982f-5ee0a5a1b1ab", "start_line": 38, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "c735e134-3362-473e-aa89-f1bc257a8943", "remote_addr": "127.0.0.1", "res": {"stderr_lines": ["error: unexpected data '{stderr_lines:'"], "deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "cmd": ["virsh", "attach-interface", "\u2013domain", "routers.sourceRouter", "\u2013type", "network", "\u2013source", "routers.networkName", "\u2013model", "virtio", "\u2013mac", "{stderr_lines:", "[],", "stdout:", "uc5:2a:18:2d:27:41\\n,", "changed:", "True,", "failed:", "False,", "stderr:", "u,", "rc:", "0,", "stdout_lines:", "[uc5:2a:18:2d:27:41]}", "\u2013config", "\u2013live"], "end": "2019-11-10 22:10:18.490999", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "start": "2019-11-10 22:10:18.457896", "stderr": "error: unexpected data '{stderr_lines:'", "delta": "0:00:00.033103", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "virsh attach-interface \u2013domain routers.sourceRouter \u2013type network \u2013source routers.networkName \u2013model virtio \u2013mac {'stderr_lines': [], 'stdout': u'c5:2a:18:2d:27:41\\n', 'changed': True, 'failed': False, 'stderr': u'', 'rc': 0, 'stdout_lines': [u'c5:2a:18:2d:27:41']} \u2013config \u2013live", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "msg": "non-zero return code"}, "play_uuid": "52540074-89e3-7d9a-482f-000000000008", "task_uuid": "52540074-89e3-7d9a-482f-00000000000f", "task": "Attach network to R1", "playbook_uuid": "98ac81b7-ab0e-47c5-8259-373f918454b6", "playbook": "routerConnectionCreation.yaml", "task_action": "command", "host": "127.0.0.1", "ignore_errors": null, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:41"}, "parent_uuid": "52540074-89e3-7d9a-482f-00000000000f"}