{"event": "runner_on_failed", "uuid": "88764a31-6e44-4260-80c1-001f8b7dbee6", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": false, \"msg\": \"network network12 not found\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "counter": 18, "pid": 20127, "created": "2019-11-10T22:16:36.181655", "end_line": 30, "runner_ident": "3c18c81e-3e3c-477d-9028-9a9c22b4ee20", "start_line": 28, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "88764a31-6e44-4260-80c1-001f8b7dbee6", "remote_addr": "127.0.0.1", "res": {"deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "_ansible_no_log": false, "changed": false, "msg": "network network12 not found", "invocation": {"module_args": {"xml": null, "name": "network12", "uri": "qemu:///system", "state": null, "command": "create", "autostart": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}}, "play_uuid": "52540074-89e3-359b-9642-000000000008", "task_uuid": "52540074-89e3-359b-9642-00000000000c", "task": "Create Virtual Network if not created", "playbook_uuid": "ffbef508-d0f9-4906-a647-60158227af95", "playbook": "routerConnectionCreation.yaml", "task_action": "virt_net", "host": "127.0.0.1", "ignore_errors": true, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:27"}, "parent_uuid": "52540074-89e3-359b-9642-00000000000c"}