{"event": "runner_on_failed", "uuid": "3518efbf-76de-4c9b-8026-ab42dbbed524", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": true, \"cmd\": [\"virsh\", \"attach-interface\", \"\u2013domain\", \"routerConnectionParams.sourceRouter\", \"\u2013type\", \"network\", \"\u2013source\", \"routers.networkName\", \"\u2013model\", \"virtio\", \"\u2013mac\", \"{stderr_lines:\", \"[],\", \"stdout:\", \"u90:b7:66:8d:e5:8c\\\\n,\", \"changed:\", \"True,\", \"failed:\", \"False,\", \"stderr:\", \"u,\", \"rc:\", \"0,\", \"stdout_lines:\", \"[u90:b7:66:8d:e5:8c]}\", \"\u2013config\", \"\u2013live\"], \"delta\": \"0:00:00.040629\", \"end\": \"2019-11-10 23:21:06.541478\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2019-11-10 23:21:06.500849\", \"stderr\": \"error: unexpected data '{stderr_lines:'\", \"stderr_lines\": [\"error: unexpected data '{stderr_lines:'\"], \"stdout\": \"\", \"stdout_lines\": []}\u001b[0m", "counter": 27, "pid": 22218, "created": "2019-11-10T23:21:06.601642", "end_line": 39, "runner_ident": "249fb64a-cd96-4662-8827-71cd0790bc43", "start_line": 38, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "3518efbf-76de-4c9b-8026-ab42dbbed524", "remote_addr": "127.0.0.1", "res": {"stderr_lines": ["error: unexpected data '{stderr_lines:'"], "deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "cmd": ["virsh", "attach-interface", "\u2013domain", "routerConnectionParams.sourceRouter", "\u2013type", "network", "\u2013source", "routers.networkName", "\u2013model", "virtio", "\u2013mac", "{stderr_lines:", "[],", "stdout:", "u90:b7:66:8d:e5:8c\\n,", "changed:", "True,", "failed:", "False,", "stderr:", "u,", "rc:", "0,", "stdout_lines:", "[u90:b7:66:8d:e5:8c]}", "\u2013config", "\u2013live"], "end": "2019-11-10 23:21:06.541478", "_ansible_no_log": false, "stdout": "", "changed": true, "rc": 1, "start": "2019-11-10 23:21:06.500849", "stderr": "error: unexpected data '{stderr_lines:'", "delta": "0:00:00.040629", "invocation": {"module_args": {"creates": null, "executable": null, "_uses_shell": false, "strip_empty_ends": true, "_raw_params": "virsh attach-interface \u2013domain routerConnectionParams.sourceRouter \u2013type network \u2013source routers.networkName \u2013model virtio \u2013mac {'stderr_lines': [], 'stdout': u'90:b7:66:8d:e5:8c\\n', 'changed': True, 'failed': False, 'stderr': u'', 'rc': 0, 'stdout_lines': [u'90:b7:66:8d:e5:8c']} \u2013config \u2013live", "removes": null, "argv": null, "warn": true, "chdir": null, "stdin_add_newline": true, "stdin": null}}, "stdout_lines": [], "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "msg": "non-zero return code"}, "play_uuid": "52540074-89e3-0e68-41f2-000000000008", "task_uuid": "52540074-89e3-0e68-41f2-00000000000f", "task": "Attach network to R1", "playbook_uuid": "bec5ef35-6b75-4463-bbde-4da4409ad465", "playbook": "routerConnectionCreation.yaml", "task_action": "command", "host": "127.0.0.1", "ignore_errors": null, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:43"}, "parent_uuid": "52540074-89e3-0e68-41f2-00000000000f"}