{"event": "runner_on_failed", "uuid": "70445f0b-f15f-43f8-83bd-3b55cceb60e5", "stdout": "\u001b[0;31mfatal: [127.0.0.1]: FAILED! => {\"ansible_facts\": {\"discovered_interpreter_python\": \"/usr/bin/python\"}, \"changed\": false, \"msg\": \"network network12 not found\"}\u001b[0m\r\n\u001b[0;36m...ignoring\u001b[0m", "counter": 19, "pid": 23036, "created": "2019-11-10T23:35:57.094366", "end_line": 30, "runner_ident": "4445b47f-4092-4bc7-945c-ec0bc663877e", "start_line": 28, "event_data": {"play_pattern": "localhost", "play": "localhost", "event_loop": null, "task_args": "", "uuid": "70445f0b-f15f-43f8-83bd-3b55cceb60e5", "remote_addr": "127.0.0.1", "res": {"deprecations": [{"msg": "Distribution Ubuntu 18.04 on host 127.0.0.1 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "_ansible_no_log": false, "changed": false, "msg": "network network12 not found", "invocation": {"module_args": {"xml": null, "name": "network12", "uri": "qemu:///system", "state": null, "command": "create", "autostart": null}}, "ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}}, "play_uuid": "52540074-89e3-f6af-d5b8-000000000008", "task_uuid": "52540074-89e3-f6af-d5b8-00000000000c", "task": "Create Virtual Network if not created", "playbook_uuid": "55eb9188-43ae-43ca-94bd-219ddafb424f", "playbook": "routerConnectionCreation.yaml", "task_action": "virt_net", "host": "127.0.0.1", "ignore_errors": true, "task_path": "/home/ece792/Team10-SDWAN/jagan/ansible_scripts/routerConnectionCreation.yaml:26"}, "parent_uuid": "52540074-89e3-f6af-d5b8-00000000000c"}